# Generated by Django 3.0.4 on 2020-05-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='a1',
            field=models.CharField(choices=[('1', 'Po'), ('0', 'Jo')], default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='a10',
            field=models.CharField(choices=[('1', 'Po'), ('0', 'Jo')], default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='a7',
            field=models.CharField(choices=[('1', 'Po'), ('0', 'Jo')], default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='a8',
            field=models.CharField(choices=[('1', 'Po'), ('0', 'Jo')], default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='gjinia',
            field=models.CharField(choices=[('0', 'Femer'), ('1', 'Mashkull')], default=None, max_length=128),
        ),
    ]
